// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: proto/logflux/v1/log.proto

package logfluxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Level int32

const (
	Level_LEVEL_UNSPECIFIED Level = 0
	Level_DEBUG             Level = 1
	Level_INFO              Level = 2
	Level_WARN              Level = 3
	Level_ERROR             Level = 4
	Level_FATAL             Level = 5
)

// Enum value maps for Level.
var (
	Level_name = map[int32]string{
		0: "LEVEL_UNSPECIFIED",
		1: "DEBUG",
		2: "INFO",
		3: "WARN",
		4: "ERROR",
		5: "FATAL",
	}
	Level_value = map[string]int32{
		"LEVEL_UNSPECIFIED": 0,
		"DEBUG":             1,
		"INFO":              2,
		"WARN":              3,
		"ERROR":             4,
		"FATAL":             5,
	}
)

func (x Level) Enum() *Level {
	p := new(Level)
	*p = x
	return p
}

func (x Level) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Level) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_logflux_v1_log_proto_enumTypes[0].Descriptor()
}

func (Level) Type() protoreflect.EnumType {
	return &file_proto_logflux_v1_log_proto_enumTypes[0]
}

func (x Level) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Level.Descriptor instead.
func (Level) EnumDescriptor() ([]byte, []int) {
	return file_proto_logflux_v1_log_proto_rawDescGZIP(), []int{0}
}

type LogEntry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServiceName     string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Environment     string                 `protobuf:"bytes,2,opt,name=environment,proto3" json:"environment,omitempty"`
	TimestampUnixMs int64                  `protobuf:"varint,3,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	Level           Level                  `protobuf:"varint,4,opt,name=level,proto3,enum=logflux.v1.Level" json:"level,omitempty"`
	Message         string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	TraceId         string                 `protobuf:"bytes,6,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Fields          map[string]string      `protobuf:"bytes,7,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // arbitrary structured metadata
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_proto_logflux_v1_log_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logflux_v1_log_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_proto_logflux_v1_log_proto_rawDescGZIP(), []int{0}
}

func (x *LogEntry) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *LogEntry) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *LogEntry) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

func (x *LogEntry) GetLevel() Level {
	if x != nil {
		return x.Level
	}
	return Level_LEVEL_UNSPECIFIED
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *LogEntry) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type StreamAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AcceptedCount int64                  `protobuf:"varint,1,opt,name=accepted_count,json=acceptedCount,proto3" json:"accepted_count,omitempty"`
	RejectedCount int64                  `protobuf:"varint,2,opt,name=rejected_count,json=rejectedCount,proto3" json:"rejected_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamAck) Reset() {
	*x = StreamAck{}
	mi := &file_proto_logflux_v1_log_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAck) ProtoMessage() {}

func (x *StreamAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logflux_v1_log_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAck.ProtoReflect.Descriptor instead.
func (*StreamAck) Descriptor() ([]byte, []int) {
	return file_proto_logflux_v1_log_proto_rawDescGZIP(), []int{1}
}

func (x *StreamAck) GetAcceptedCount() int64 {
	if x != nil {
		return x.AcceptedCount
	}
	return 0
}

func (x *StreamAck) GetRejectedCount() int64 {
	if x != nil {
		return x.RejectedCount
	}
	return 0
}

var File_proto_logflux_v1_log_proto protoreflect.FileDescriptor

const file_proto_logflux_v1_log_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/logflux/v1/log.proto\x12\n" +
	"logflux.v1\"\xce\x02\n" +
	"\bLogEntry\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12 \n" +
	"\venvironment\x18\x02 \x01(\tR\venvironment\x12*\n" +
	"\x11timestamp_unix_ms\x18\x03 \x01(\x03R\x0ftimestampUnixMs\x12'\n" +
	"\x05level\x18\x04 \x01(\x0e2\x11.logflux.v1.LevelR\x05level\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x19\n" +
	"\btrace_id\x18\x06 \x01(\tR\atraceId\x128\n" +
	"\x06fields\x18\a \x03(\v2 .logflux.v1.LogEntry.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Y\n" +
	"\tStreamAck\x12%\n" +
	"\x0eaccepted_count\x18\x01 \x01(\x03R\racceptedCount\x12%\n" +
	"\x0erejected_count\x18\x02 \x01(\x03R\rrejectedCount*S\n" +
	"\x05Level\x12\x15\n" +
	"\x11LEVEL_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05DEBUG\x10\x01\x12\b\n" +
	"\x04INFO\x10\x02\x12\b\n" +
	"\x04WARN\x10\x03\x12\t\n" +
	"\x05ERROR\x10\x04\x12\t\n" +
	"\x05FATAL\x10\x052H\n" +
	"\tLogIngest\x12;\n" +
	"\n" +
	"StreamLogs\x12\x14.logflux.v1.LogEntry\x1a\x15.logflux.v1.StreamAck(\x01B?Z=github.com/TohidTonekaboni/LogFlux/proto/logflux/v1;logfluxv1b\x06proto3"

var (
	file_proto_logflux_v1_log_proto_rawDescOnce sync.Once
	file_proto_logflux_v1_log_proto_rawDescData []byte
)

func file_proto_logflux_v1_log_proto_rawDescGZIP() []byte {
	file_proto_logflux_v1_log_proto_rawDescOnce.Do(func() {
		file_proto_logflux_v1_log_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_logflux_v1_log_proto_rawDesc), len(file_proto_logflux_v1_log_proto_rawDesc)))
	})
	return file_proto_logflux_v1_log_proto_rawDescData
}

var file_proto_logflux_v1_log_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_logflux_v1_log_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_logflux_v1_log_proto_goTypes = []any{
	(Level)(0),        // 0: logflux.v1.Level
	(*LogEntry)(nil),  // 1: logflux.v1.LogEntry
	(*StreamAck)(nil), // 2: logflux.v1.StreamAck
	nil,               // 3: logflux.v1.LogEntry.FieldsEntry
}
var file_proto_logflux_v1_log_proto_depIdxs = []int32{
	0, // 0: logflux.v1.LogEntry.level:type_name -> logflux.v1.Level
	3, // 1: logflux.v1.LogEntry.fields:type_name -> logflux.v1.LogEntry.FieldsEntry
	1, // 2: logflux.v1.LogIngest.StreamLogs:input_type -> logflux.v1.LogEntry
	2, // 3: logflux.v1.LogIngest.StreamLogs:output_type -> logflux.v1.StreamAck
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_logflux_v1_log_proto_init() }
func file_proto_logflux_v1_log_proto_init() {
	if File_proto_logflux_v1_log_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_logflux_v1_log_proto_rawDesc), len(file_proto_logflux_v1_log_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_logflux_v1_log_proto_goTypes,
		DependencyIndexes: file_proto_logflux_v1_log_proto_depIdxs,
		EnumInfos:         file_proto_logflux_v1_log_proto_enumTypes,
		MessageInfos:      file_proto_logflux_v1_log_proto_msgTypes,
	}.Build()
	File_proto_logflux_v1_log_proto = out.File
	file_proto_logflux_v1_log_proto_goTypes = nil
	file_proto_logflux_v1_log_proto_depIdxs = nil
}
